# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-13 18:19
from __future__ import unicode_literals

from django.db import migrations

def foward_func(apps, schema_editor):
    Channel = apps.get_model("channels", "Channel")
    channel = Channel.objects.get(slug="boehringer")

    Category = apps.get_model("projects", "Category")
    category = Category.objects.create(name="export-to-boehringer", slug="export-to-boehringer", channel=channel)


def rewind_func(apps, schema_editor):
    return True


class Migration(migrations.Migration):

    dependencies = [
        ('boehringer', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(foward_func, rewind_func)
    ]
