# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 16:07
from __future__ import unicode_literals

from django.db import migrations
from ovp.apps.core.helpers import generate_slug

class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_channel_slug'),
    ]

    operations = [
    ]
