# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-03 08:41
from __future__ import unicode_literals

from django.db import migrations


def foward_func(apps, schema_editor):
    return True

def rewind_func(apps, schema_editor):
    return True


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0007_channelsetting'),
    ]

    operations = [
        migrations.RunPython(foward_func, rewind_func)
    ]
