# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-03 08:41
from __future__ import unicode_literals

from django.db import migrations


def foward_func(apps, schema_editor):
    Channel = apps.get_model('channels', 'Channel')
    ChannelSetting = apps.get_model('channels', 'ChannelSetting')
    channel = Channel.objects.get(pk=1)
    ChannelSetting.objects.create(key="DISABLE_EMAIL", value="userInvited-toMemberInviter", channel=channel)
    ChannelSetting.objects.create(key="DISABLE_EMAIL", value="userInvited-toOwner", channel=channel)
    ChannelSetting.objects.create(key="DISABLE_EMAIL", value="userInvited-toOwnerInviter", channel=channel)
    ChannelSetting.objects.create(key="DISABLE_EMAIL", value="userInvitedRevoked-toMemberInviter", channel=channel)
    ChannelSetting.objects.create(key="DISABLE_EMAIL", value="userInvitedRevoked-toOwner", channel=channel)
    ChannelSetting.objects.create(key="DISABLE_EMAIL", value="userInvitedRevoked-toOwnerInviter", channel=channel)
    ChannelSetting.objects.create(key="DISABLE_EMAIL", value="userInvitedRevoked-toUser", channel=channel)
    ChannelSetting.objects.create(key="DISABLE_EMAIL", value="userJoined-toUser", channel=channel)
    ChannelSetting.objects.create(key="DISABLE_EMAIL", value="userLeft-toOwner", channel=channel)
    ChannelSetting.objects.create(key="DISABLE_EMAIL", value="userLeft-toUser", channel=channel)
    ChannelSetting.objects.create(key="DISABLE_EMAIL", value="userRemoved-toOwner", channel=channel)
    ChannelSetting.objects.create(key="DISABLE_EMAIL", value="userRemoved-toUser", channel=channel)
    return True

def rewind_func(apps, schema_editor):
    ChannelSetting = apps.get_model('channels', 'ChannelSetting')
    ChannelSetting.objects.filter(key="DISABLE_EMAIL", value="userInvited-toMemberInviter").delete()
    ChannelSetting.objects.filter(key="DISABLE_EMAIL", value="userInvited-toOwner").delete()
    ChannelSetting.objects.filter(key="DISABLE_EMAIL", value="userInvited-toOwnerInviter").delete()
    ChannelSetting.objects.filter(key="DISABLE_EMAIL", value="userInvitedRevoked-toMemberInviter").delete()
    ChannelSetting.objects.filter(key="DISABLE_EMAIL", value="userInvitedRevoked-toOwner").delete()
    ChannelSetting.objects.filter(key="DISABLE_EMAIL", value="userInvitedRevoked-toOwnerInviter").delete()
    ChannelSetting.objects.filter(key="DISABLE_EMAIL", value="userInvitedRevoked-toUser").delete()
    ChannelSetting.objects.filter(key="DISABLE_EMAIL", value="userJoined-toUser").delete()
    ChannelSetting.objects.filter(key="DISABLE_EMAIL", value="userLeft-toOwner").delete()
    ChannelSetting.objects.filter(key="DISABLE_EMAIL", value="userLeft-toUser").delete()
    ChannelSetting.objects.filter(key="DISABLE_EMAIL", value="userRemoved-toOwner").delete()
    ChannelSetting.objects.filter(key="DISABLE_EMAIL", value="userRemoved-toUser").delete()
    return True


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0007_channelsetting'),
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(foward_func, rewind_func)
    ]
