# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-04 20:45
from __future__ import unicode_literals

from django.db import migrations


def foward_func(apps, schema_editor):
    Channel = apps.get_model('channels', 'Channel')
    channel = Channel.objects.get(slug='default')
    RatingParameter = apps.get_model('ratings', 'RatingParameter')
    RatingParameter.objects.create(slug='project-how-was-it', type=1, channel=channel)
    RatingParameter.objects.create(slug='project-score', type=2, channel=channel)
    RatingParameter.objects.create(slug='volunteer-score', type=2, channel=channel)
    return True

def rewind_func(apps, schema_editor):
    return True

class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_disable_emails'),
        ('channels', '0007_channelsetting'),
        ('ratings', '0009_auto_20181029_1052'),
    ]

    operations = [
        migrations.RunPython(foward_func, rewind_func)
    ]
