# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-15 18:03
from __future__ import unicode_literals

from django.db import migrations

def foward_func(apps, schema_editor):
    Channel = apps.get_model('channels', 'Channel')
    channel = Channel.objects.get(slug='default')
    RatingParameter = apps.get_model('ratings', 'RatingParameter')
    RatingParameter.objects.create(slug='user-has-shown', type=3, channel=channel)
    return True

def rewind_func(apps, schema_editor):
    return True

class Migration(migrations.Migration):

    dependencies = [
        ('default', '0003_auto_20181104_1845'),
    ]

    operations = [
        migrations.RunPython(foward_func, rewind_func)
    ]
