# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 16:07
from __future__ import unicode_literals

from django.db import migrations

def foward_func(apps, schema_editor):
    Channel = apps.get_model("channels", "Channel")
    channel = Channel.objects.create(name="Parceiros voluntários", slug="pv")

    # We freeze default channels skills and causes because
    # post_save signals are not sent from migrations
    from ovp.apps.core.models.skill import skills
    from ovp.apps.core.models.cause import causes

    Skill = apps.get_model("core", "Skill")
    Cause = apps.get_model("core", "Cause")

    for skill in skills:
      Skill.objects.create(name=skill, channel=channel)

    for cause in causes:
      Cause.objects.create(name=cause, channel=channel)

def rewind_func(apps, schema_editor):
    Channel = apps.get_model("channels", "Channel")
    Channel.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_channel_slug'),
    ]

    operations = [
        migrations.RunPython(foward_func, rewind_func)
    ]
