# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 18:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pv', '0002_pvuserinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvuserinfo',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
            preserve_default=False,
        ),
    ]
