# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 18:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pv', '0003_pvuserinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvuserinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
