# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0007_channelsetting'),
        ('pv', '0006_auto_20170918_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvmeetingappointment',
            name='channel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pvmeetingappointment_channel', to='channels.Channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pvmeetingdate',
            name='channel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pvmeetingdate_channel', to='channels.Channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pvuserinfo',
            name='channel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pvuserinfo_channel', to='channels.Channel'),
            preserve_default=False,
        ),
    ]
