# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ovp.apps.channels.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0007_channelsetting'),
        ('pv', '0007_auto_20170918_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='PVMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvmeeting_channel', to='channels.Channel')),
            ],
            options={
                'abstract': False,
            },
            bases=(ovp.apps.channels.models.mixins.ChannelCreatorMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='pvmeetingdate',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='pvmeetingappointment',
            name='meeting_date',
        ),
        migrations.DeleteModel(
            name='PVMeetingDate',
        ),
    ]
