# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pv', '0008_auto_20170918_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvmeetingappointment',
            name='meeting',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pv.PVMeeting'),
            preserve_default=False,
        ),
    ]
