# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pv', '0009_pvmeetingappointment_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvmeetingappointment',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='pv.PVMeeting'),
        ),
    ]
