# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20171005_1902'),
        ('pv', '0010_auto_20170919_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvmeeting',
            name='address',
            field=models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.GoogleAddress', verbose_name='address'),
        ),
        migrations.AddField(
            model_name='pvmeeting',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
