# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv', '0011_auto_20171024_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvmeeting',
            name='max_appointments',
            field=models.IntegerField(default=40),
        ),
    ]
