# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv', '0012_pvmeeting_max_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvmeetingappointment',
            name='user_did_not_show_up',
            field=models.BooleanField(default=False),
        ),
    ]
