# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 15:38
from __future__ import unicode_literals

from django.db import migrations

from django.contrib.auth.management import create_permissions

def migrate_permissions(apps, schema_editor):
  for app_config in apps.get_app_configs():
    app_config.models_module = True
    create_permissions(app_config, apps=apps, verbosity=0)
    app_config.models_module = None

def foward_func(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    group = Group.objects.create(name='PV Meeting Editor')

    Permission = apps.get_model('auth', 'Permission')
    permission_list = ['add_pvmeeting', 'change_pvmeeting', 'delete_pvmeeting', 'add_pvmeetingappointment', 'change_pvmeetingappointment', 'delete_pvmeetingappointment', 'add_pvuserinfo', 'change_pvuserinfo', 'delete_pvuserinfo']
    for permission in permission_list:
      permission_object = Permission.objects.get(codename=permission)
      group.permissions.add(permission_object)
      pass
    return True

def rewind_func(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='PV Meeting Editor').delete()
    return True

class Migration(migrations.Migration):

    dependencies = [
        ('pv', '0013_pvmeetingappointment_did_not_show_up'),
    ]

    operations = [
        migrations.RunPython(migrate_permissions, migrate_permissions),
        migrations.RunPython(foward_func, rewind_func)
    ]
