# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 15:38
from __future__ import unicode_literals

from django.db import migrations


def foward_func(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    group = Group.objects.create(name='PV Meeting Editor')

    Permission = apps.get_model('auth', 'Permission')
    permission_list = ['add_pvmeeting', 'change_pvmeeting', 'delete_pvmeeting', 'add_pvmeetingappointment', 'change_pvmeetingappointment', 'delete_pvmeetingappointment', 'add_pvmeetingdate', 'change_pvmeetingdate', 'delete_pvmeetingdate', 'add_pvuserinfo', 'change_pvuserinfo', 'delete_pvuserinfo']
    for permission in permission_list:
      permission_object = Permission.objects.get(codename=permission)
      group.permissions.add(permission_object)
    return True

def rewind_func(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='PV Meeting Editor').delete()
    return True

class Migration(migrations.Migration):

    dependencies = [
        ('pv', '0013_pvmeetingappointment_did_not_show_up'),
    ]

    operations = [
        migrations.RunPython(foward_func, rewind_func)
    ]
