# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 17:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pv', '0014_auto_20171030_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pvmeeting',
            options={'verbose_name': 'PV Meeting', 'verbose_name_plural': 'PV Meetings'},
        ),
        migrations.AlterModelOptions(
            name='pvmeetingappointment',
            options={'verbose_name': 'PV Meeting Appointment', 'verbose_name_plural': 'PV Meetings Appointments'},
        ),
        migrations.AlterModelOptions(
            name='pvuserinfo',
            options={'verbose_name': 'PV User Info', 'verbose_name_plural': 'PV Users Info'},
        ),
        migrations.AlterField(
            model_name='pvmeeting',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='pvmeeting',
            name='max_appointments',
            field=models.IntegerField(default=40, verbose_name='Maximum appointments'),
        ),
        migrations.AlterField(
            model_name='pvmeeting',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='pvmeetingappointment',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='pv.PVMeeting', verbose_name='meeting'),
        ),
        migrations.AlterField(
            model_name='pvmeetingappointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='pvmeetingappointment',
            name='user_did_not_show_up',
            field=models.BooleanField(default=False, verbose_name='User did not show up'),
        ),
        migrations.AlterField(
            model_name='pvuserinfo',
            name='can_apply',
            field=models.BooleanField(default=False, verbose_name='Can Apply'),
        ),
        migrations.AlterField(
            model_name='pvuserinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
