# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-30 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_availability_channel'),
        ('pv', '0015_auto_20171204_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pvmeeting',
            name='address',
        ),
        migrations.AddField(
            model_name='pvmeeting',
            name='address',
            field=models.ManyToManyField(blank=True, db_constraint=False, null=True, to='core.GoogleAddress', verbose_name='address'),
        ),
    ]
