# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-30 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_availability_channel'),
        ('pv', '0016_auto_20180129_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pvmeeting',
            name='address',
        ),
        migrations.AddField(
            model_name='pvmeeting',
            name='address',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.GoogleAddress', verbose_name='address'),
        ),
    ]
