# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-26 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv', '0017_auto_20180129_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvmeetingappointment',
            name='special_conditions',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Special Conditions'),
        ),
    ]
